export {default as Sound} from 'react-sound'
export {Play} from './Play'
export {Volume} from './Volume'
export {Timer} from './Timer'
export {Progress} from './Progress'
export {Speed} from './Speed'
